blank_issues_enabled: false
contact_links:
  - name: List of Completed Requests and Issues 
    url: https://github.com/ccao-data/public/issues?q=is%3Aissue+is%3Aclosed
    about: Please check this before creating a new issue
  - name: Private Questions
    url: mailto:Assessor.Data@cookcountyil.gov
    about: Please ask private and sensitive questions via email
