name: Data request
description: Create a new bulk data request
labels: ["data request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to make a data request! This issue template will help you clearly articulate your request. Please read the template carefully, and populate each section as completely as you can.
  - type: textarea
    id: general-description 
    attributes:
      label: General description
      description: |
        Please use this space to describe, in your own words, the data you are requesting. Be as specific as possible.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: |
        Often, it is helpful for us to understand how the data will be used. In this space, please describe your use case.
    validations:
      required: true
  - type: textarea
    id: universe
    attributes:
      label: Universe
      description: |
        Please describe the universe of the data you are requesting.
      placeholder: |
        - All single-family PINs in Lyons township
        - Every unique combination of postal address and PIN in the City of Chicago
        - Every PIN in a Special Service Area in the City of Chicago
    validations:
      required: true
  - type: textarea
    id: unit
    attributes:
      label: Unit of observation
      description: |
        Please describe the unit of observation for the data you are requesting. A unit of observation is the unique identifier for each row in your data.
      placeholder: |
        - Individual Property Index Numbers (PINs)
        - Cook County townships
    validations:
      required: true
  - type: textarea
    id: restrictions
    attributes:
      label: Restrictions and exclusions
      description: |
        Please describe any specific restrictions or exclusions from your data. For example, if you defined your universe as "single-family", you should define your expectations about what that means. For example, do you consider a condominium a single-family property?
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Data delivery format
      description: |
        Please choose a preferred delivery format. Files will be delivered via a public S3 bucket. Choose "Open Data asset" if you think your data will be of public interest i.e. it will be frequently requested.
      multiple: false
      options:
        - CSV
        - XLSX
        - Parquet
        - Open Data asset
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Citation and use of Assessor data
      description: |
        By submitting this issue ticket, I certify the following:
          - I will cite the Cook County Assessor's Office. Publications and other materials leveraging this data should clearly and appropriately cite the CCAO, and this particular issue ticket.
          - I will use this data to do good.
      options:
        - label: I agree to the above terms.
          required: true

