on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

name: super-linter

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Exclude some linters that we don't care about
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JSCPD: false
          VALIDATE_TRIVY: false
          # Pre-commit runs in a separate workflow
          VALIDATE_PRE_COMMIT: false
          # Pre-commit handles sqlfluff and markdownlint
          VALIDATE_SQLFLUFF: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          # Exclude autogenerated HTML files
          FILTER_REGEX_EXCLUDE: .*analyses/tax-share-analysis/residential_tax_share_analysis_report.html$
